### PR TITLE
Chore: improve eslint & ts, deactivate nx daemon

### PR DESCRIPTION
**Pull request by Laurin-W**
* Add roughly the same configuration that is now used for activitypods
* Remove a bug that made semapps middleware eslint to produce errors (couldn't find the ts config root)
* fix minor errors
* ~~frontend: add typecheck before build~~
    * Without `tsc --noEmit` before `parcel build`, the build even works when there are type errors. But running `yarn build` in the frontend root emits error messages (even though it seems to build), running `yarn build` in a package emits warnings. I suppose it is fine, looking at the speed improvements of not using `tsc` additionally during build. See revert at https://github.com/assemblee-virtuelle/semapps/pull/1195

### CODE REVIEW

**Review by srosset81 — APPROVED** [review]

**Comment by Laurin-W** [comment]
I now also deactivated the nx daemon process, since it was eating loads of resources even when there were no processes running or file changes happening.

**Comment by mguihal** [comment]
> Without tsc --noEmit before parcel build, the build even works when there are type errors. But running yarn build in the frontend root emits error messages (even though it seems to build), running yarn build in a package emits warnings. I suppose it is fine, looking at the speed improvements of not using tsc additionally during build.

I understand your issues with build time (it didn't bother me until now but maybe some packages are slower than another), but I would suggest to still enforce typecheck is ok with a pre-commit hook to prevent from publishing correct js code but with incorrect types if any. What do you think?

**Comment by srosset81** [comment]
What about doing the typecheck on `yarn run build` but not on `yarn run watch` ?

**Comment by Laurin-W** [comment]
To me, both or your proposals sound like viable options. Even though @srosset81's proposal might not prevent people from accidentally commiting errorneous code. On the other hand it can be quite annoying when doing multiple commits in a very short time, to structure changes you made.

I'll check, if there is a pre-push hook or so which might do the job.

**Comment by Laurin-W** [comment]
See my PR https://github.com/assemblee-virtuelle/semapps/pull/1201

**Pull request merged**
