### PR TITLE
Update how-to.md

### PR DESCRIPTION
**Pull request by GuillaumeAV**
C'est un test!

### CODE REVIEW

**Comment by jmvanel** [comment]
Le bouton COMMENCER

donne cette erreur :

Page Not Found

We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL
and let them know their link is broken.


Jean-Marc Vanel
<http://semantic-forms.cc:9112/display?displayuri=http://jmvanel.free.fr/jmv.rdf%23me>
+33 (0)6 89 16 29 52
Twitter: @jmvanel , @jmvanel_fr ; chat: irc://irc.freenode.net#eulergui
 Chroniques jardin
<http://semantic-forms.cc:1952/history?uri=http%3A%2F%2Fdbpedia.org%2Fresource%2FChronicle>

**Comment by ReX-AV-Gab** [comment]
OK mec !

**Review by srosset81 — CHANGES_REQUESTED** [review]
Travail baclé ! ;-)

**Comment by GuillaumeAV** [comment]
Olala je suis brisé dans mon apprentissage et mon amour propre Seb ;-)

**Review by ReX-AV-Gab — APPROVED** [review]
J'approve

**Pull request closed without merging**
