### PR TITLE
Fix: Anonymize uploaded files

### PR DESCRIPTION
**Pull request by mguihal**
Hi,

Currently, when we upload a file (for example to illustrate a resource), the name of the created resource keeps the name of the local file. This may cause some unwanted behaviours:
- **Privacy issues:** If the user who uploaded the named it with personal information in the filename, these are kept on the server
- **Duplication issues:** If a file is uploaded more than one time, its name is currently duplicated, with a number added after its extension (ex: https://data.virtual-assembly.org/files/logo_av1.png1) which can confuse users, screen readers, robots, etc.

I propose in this PR to replace local file names by an UUID generated name (keeping the file extension) [commit 49dd8373b94b606356b3ebf015d99299674c3fb8]

I also typed the modified file in Typescript. Due to dependencies I started to type data-provider config object, this could surely be improved to be more restrictive, but as a first typing pass I think it's ok. I changed the attribute `noImplicitAny` to true in the Typescript config, to prevent from files with unknown variables types to be validated [commit e943c37795d33a4a08cd7e5d73efbce14410d9e8]

### CODE REVIEW

**Comment by srosset81** [comment]
If you don't pass any slug in the header, a UUID is used by the middleware.
You just lose the extension but is it a problem if the MIME type is correctly returned ?
What bothers me is that bundling the uuid library adds 9kb (it is not used by any other package, except Lerna but it's a dev dependency). Also it duplicates the code from the middleware, which adds more maintenance.

**Comment by mguihal** [comment]
My bad, I missed the point that file name could be computed in LDP service if the slug was not sent! 
It's working well without the extension, but I think it's better with. For users who want to download a uploaded image for example, it's more user-friendly if the extension is already set.

I propose in this commit fd3964274b3f8b116f9f937b27c68c7a4a70e034 that we only send the file extension to the LDP service, which compute the correct slug with uuid if extension is found in headers.

**Comment by srosset81** [comment]
I'm a bit unconfortable with adding new HTTP headers since, with SemApps, we try to stay as close as possible to standards and I'm not aware of an existing header for suggesting file extensions (the `Slug` header is in the LDP specs).
The only custom header we handle for now is `JsonLdContext` and it going to be thoroughly documented.
If keeping the extension seems important to you (and that was my question), then maybe your original solution was more appropriate to keep up with the standards ?
Another solution could be to guess the extension from the MIME type that is always sent along with binaries. There is a  [package](https://github.com/jshttp/mime-db) for that (used by 26M Github repositories !). It won't work with unknown MIME type, but then we could just do without extension ? What do you think ?

I'm sorry to make you rewrite your code for such precious core contributions. It could be interesting to see how we could improve our processes. The best practice would probably be to first post issues, and to do a PR only when they are approved.

Ping @Laurin-W if you have some opinions

**Comment by mguihal** [comment]
> I'm a bit unconfortable with adding new HTTP headers since, with SemApps, we try to stay as close as possible to standards and I'm not aware of an existing header for suggesting file extensions (the Slug header is in the LDP specs). The only custom header we handle for now is JsonLdContext and it going to be thoroughly documented.

It's ok, I didn't know Slug header was in some standards (I'm kind of a newbie in this domain, and not so aware of all standards sry), but totally ok to stay as close as possible to standards.

> If keeping the extension seems important to you (and that was my question), then maybe your original solution was more appropriate to keep up with the standards ?

I agreed with you on the addition of a new lib in frontend package which could be annoying, so I prefer your latest proposition.

> Another solution could be to guess the extension from the MIME type that is always sent along with binaries. There is a [package](https://github.com/jshttp/mime-db) for that (used by 26M Github repositories !). It won't work with unknown MIME type, but then we could just do without extension ? What do you think ?

I amended my commit 820bf842d905315ee2da922e61e6dc8a39c9bd40 with that solution and it's working well too :)

> I'm sorry to make you rewrite your code for such precious core contributions. It could be interesting to see how we could improve our processes. The best practice would probably be to first post issues, and to do a PR only when they are approved.

No problem. I haven't all these issues in mind when I did this (small) change. For bigger changes it could be best to first post an issue. Event if sometimes it's easier and faster to work on a minimal implemented solution to see all implicated changes I think.

**Review by srosset81 — APPROVED** [review]

**Pull request merged**
